name: C1
on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/1 * * * *'
jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Test the jobs
        run: |
          echo "just another test"
